/*-
 * #%L
 * IJ2 commands that use bio-formats to create pyramidal ome.tiff
 * %%
 * Copyright (C) 2018 - 2026 ECOLE POLYTECHNIQUE FEDERALE DE LAUSANNE, Switzerland, BioImaging And Optics Platform (BIOP)
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as
 * published by the Free Software Foundation, either version 2 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/gpl-2.0.html>.
 * #L%
 */
package ch.epfl.biop.kheops.ometiff;

import org.junit.Ignore;
import org.junit.Test;

import java.util.Random;

import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertEquals;

/**
 * Tests of {@link AverageImageScaler}, the class which builds a resolution
 * level of the pyramid from the previous one.
 * <p>
 * The expected result is defined by {@link #blockAverage} below: an output
 * pixel is the average of the {@code scale x scale} block of source pixels it
 * covers, the columns and rows which do not fit in a whole block being
 * discarded. This is the behaviour the exporter documents ("downscaled images
 * are generated by computing an average (in XY) over the previous higher
 * resolution scale").
 * <p>
 * The parameters are the ones {@link OMETiffExporter} actually passes:
 * big endian samples, 1 channel for grayscale images and 3 planar channels for
 * RGB ones.
 */
public class AverageImageScalerTest {

	// ------------------------------------------------------- reference scaler

	/**
	 * Straightforward, obviously correct implementation of the averaging: for
	 * every output sample, average the {@code scale x scale} source samples it
	 * covers.
	 *
	 * @param src source samples, big endian
	 * @param width width of the source image, in pixels
	 * @param height height of the source image, in pixels
	 * @param scale downsampling factor
	 * @param bytesPerPixel number of bytes of a single sample
	 * @param floatingPoint whether the samples are floats
	 * @param channels number of channels
	 * @param interleaved whether the channels are interleaved (RGBRGB...) or
	 *          stored one after the other (RR...GG...BB...)
	 * @return the downsampled samples, in the same layout as the source
	 */
	private static byte[] blockAverage(byte[] src, int width, int height,
		int scale, int bytesPerPixel, boolean floatingPoint, int channels,
		boolean interleaved)
	{
		int newW = width / scale;
		int newH = height / scale;
		byte[] out = new byte[newW * newH * channels * bytesPerPixel];
		for (int c = 0; c < channels; c++) {
			for (int y = 0; y < newH; y++) {
				for (int x = 0; x < newW; x++) {
					double sum = 0;
					for (int dy = 0; dy < scale; dy++) {
						for (int dx = 0; dx < scale; dx++) {
							sum += get(src, index(scale * x + dx, scale * y + dy, c, width,
								height, channels, interleaved), bytesPerPixel, floatingPoint);
						}
					}
					int nSamples = scale * scale;
					// Integer types are averaged with an integer division, as the
					// scaler does
					double average = floatingPoint ? sum / nSamples : (long) sum /
						nSamples;
					set(out, index(x, y, c, newW, newH, channels, interleaved), average,
						bytesPerPixel, floatingPoint);
				}
			}
		}
		return out;
	}

	/** @return the index, in samples, of the sample (x, y) of a channel */
	private static int index(int x, int y, int c, int width, int height,
		int channels, boolean interleaved)
	{
		return interleaved ? (y * width + x) * channels + c : c * width * height + y *
			width + x;
	}

	/** @return the value of a sample, decoded as big endian */
	private static double get(byte[] bytes, int sample, int bytesPerPixel,
		boolean floatingPoint)
	{
		int offset = sample * bytesPerPixel;
		int bits = 0;
		for (int b = 0; b < bytesPerPixel; b++) {
			bits = (bits << 8) | (bytes[offset + b] & 0xFF);
		}
		return floatingPoint ? Float.intBitsToFloat(bits) : bits;
	}

	/** Writes a sample as big endian */
	private static void set(byte[] bytes, int sample, double value,
		int bytesPerPixel, boolean floatingPoint)
	{
		int offset = sample * bytesPerPixel;
		int bits = floatingPoint ? Float.floatToIntBits((float) value) : (int) value;
		for (int b = 0; b < bytesPerPixel; b++) {
			bytes[offset + b] = (byte) (bits >>> (8 * (bytesPerPixel - 1 - b)));
		}
	}

	// -------------------------------------------------------- test image data

	/** @return pseudo random samples, the same ones for a given seed */
	private static byte[] randomBytes(int nSamples, int bytesPerPixel,
		boolean floatingPoint, int seed)
	{
		byte[] bytes = new byte[nSamples * bytesPerPixel];
		Random random = new Random(seed);
		for (int s = 0; s < nSamples; s++) {
			// Floats are given a fractional part, which is precisely what an
			// average has to preserve
			double value = floatingPoint ? random.nextDouble() * 4 : random.nextInt(
				1 << (8 * Math.min(bytesPerPixel, 2)));
			set(bytes, s, value, bytesPerPixel, floatingPoint);
		}
		return bytes;
	}

	private void check(int width, int height, int scale, int bytesPerPixel,
		boolean floatingPoint, int channels, boolean interleaved)
	{
		byte[] src = randomBytes(width * height * channels, bytesPerPixel,
			floatingPoint, 42);
		byte[] expected = blockAverage(src, width, height, scale, bytesPerPixel,
			floatingPoint, channels, interleaved);
		byte[] actual = new AverageImageScaler().downsample(src, width, height,
			scale, bytesPerPixel, false, floatingPoint, channels, interleaved);
		String context = String.format(
			"%dx%d, scale %d, %d bytes/sample, float %b, %d channel(s), interleaved %b",
			width, height, scale, bytesPerPixel, floatingPoint, channels, interleaved);
		assertEquals(context + ": wrong output size", expected.length,
			actual.length);
		assertArrayEquals(context, expected, actual);
	}

	// ------------------------------------------------------------------ tests

	/** 8 bits grayscale, the simplest case */
	@Test
	public void downsample8BitsGray() {
		check(64, 64, 2, 1, false, 1, false);
		check(1024, 512, 2, 1, false, 1, false);
	}

	/** 16 bits grayscale, the most common Kheops input */
	@Test
	public void downsample16BitsGray() {
		check(64, 64, 2, 2, false, 1, false);
		check(1024, 512, 2, 2, false, 1, false);
	}

	/** 32 bits floats have to keep their fractional part */
	@Test
	public void downsample32BitsFloatGray() {
		check(64, 64, 2, 4, true, 1, false);
	}

	/** RGB images, as exported from an ARGBType source */
	@Test
	public void downsample8BitsRGBPlanar() {
		check(64, 64, 2, 1, false, 3, false);
	}

	@Test
	public void downsample8BitsRGBInterleaved() {
		check(64, 64, 2, 1, false, 3, true);
	}

	/**
	 * The tiles at the right and bottom edges of an image are cropped, so their
	 * size is not necessarily even: the last column and row are then dropped.
	 */
	@Test
	public void downsampleOddSizes() {
		check(63, 65, 2, 1, false, 1, false);
		check(63, 65, 2, 2, false, 1, false);
		check(101, 17, 2, 2, false, 1, false);
		check(63, 65, 2, 1, false, 3, false);
	}

	/** The downsampling factor is configurable, and not necessarily 2 */
	@Test
	public void downsampleOtherScaleFactors() {
		check(64, 64, 4, 2, false, 1, false);
		check(81, 81, 3, 2, false, 1, false);
		check(64, 64, 8, 1, false, 1, false);
	}

	/**
	 * A cropped tile whose size is far from a multiple of the scale factor: the
	 * source pixels which do not fit in a whole block should simply be dropped.
	 * <p>
	 * Known defect: with a scale factor of 3 or more and a size far from a
	 * multiple of it, the scaler spreads its sampling across the tile instead of
	 * averaging contiguous blocks. Unreachable at the default downsample of 2.
	 */
	@Ignore("known defect, unreachable at the default downsample factor of 2")
	@Test
	public void downsampleSizeNotMultipleOfScaleFactor() {
		check(11, 11, 4, 1, false, 1, false);
		check(30, 14, 4, 2, false, 1, false);
	}

	/** A scale factor of 1 should leave the image untouched */
	@Test
	public void downsampleByOneIsIdentity() {
		byte[] src = randomBytes(32 * 32, 2, false, 7);
		byte[] actual = new AverageImageScaler().downsample(src, 32, 32, 1, 2,
			false, false, 1, false);
		assertArrayEquals(src, actual);
	}

	/**
	 * The scaler takes a {@code littleEndian} flag. The exporter always writes
	 * big endian, so this only documents what the flag currently does.
	 * <p>
	 * Known defect: the {@code littleEndian} argument is ignored. Dormant, as
	 * {@link OMETiffExporter} always writes big endian.
	 */
	@Ignore("known defect, dormant: the exporter always writes big endian")
	@Test
	public void downsample16BitsLittleEndian() {
		int width = 32, height = 32, scale = 2;
		// Little endian source: build a big endian one and swap the two bytes
		byte[] bigEndian = randomBytes(width * height, 2, false, 3);
		byte[] littleEndian = new byte[bigEndian.length];
		for (int i = 0; i < bigEndian.length; i += 2) {
			littleEndian[i] = bigEndian[i + 1];
			littleEndian[i + 1] = bigEndian[i];
		}
		byte[] expectedBigEndian = blockAverage(bigEndian, width, height, scale, 2,
			false, 1, false);
		byte[] expected = new byte[expectedBigEndian.length];
		for (int i = 0; i < expectedBigEndian.length; i += 2) {
			expected[i] = expectedBigEndian[i + 1];
			expected[i + 1] = expectedBigEndian[i];
		}
		byte[] actual = new AverageImageScaler().downsample(littleEndian, width,
			height, scale, 2, true, false, 1, false);
		assertArrayEquals(expected, actual);
	}
}
